using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using CodeGenerator;


public static partial class  CSharpCodeGenerator
{
	public static void ServerInterface(TextWriter writer, string ClassName, string prefix, List<Function> Functions)
	{
		writer.WriteLine("// Generated by the rpc compiler.  DO NOT EDIT!");
		writer.WriteLine("using System;");
		writer.WriteLine("using System.Collections;");
		writer.WriteLine("using System.Threading.Tasks;");
		writer.WriteLine("using System.Collections.Generic;");
		writer.WriteLine("using Network;");
		writer.WriteLine("using ProtoBuf;");
		writer.WriteLine("using DataContract;");
		writer.WriteLine();
		writer.WriteLine("namespace " + "GameServer");
		writer.WriteLine("{");
		writer.WriteLine("");
		writer.WriteLine("    interface " + ClassName);
		writer.WriteLine("    {");
		foreach (Function current in Functions)
		{
			if ( CallDirection.Client2GameServer!=current.Direction)
			{
				continue;
			}
			writer.Write(Utility.CreateCSharpComment("        ", current.Comment));

			var retString = (0 == current.RetType.CompareTo("void")) ? "void " : "Task<ReturnValues<" + TypeDef.ConvertProtoType2CSType(current.RetType) + ">> ";
			var funcLine = string.Concat(new string[]
			{
				"        ",
				retString,
				current.FunctionName,
				" (IConnection conn"
			});
			foreach (var argument in current.Args)
			{
				funcLine = string.Concat(funcLine, 
					", ",
					TypeDef.ConvertProtoType2CSType(argument.Type),
					" ",
					argument.Name);
			}
			funcLine += ");";
			writer.WriteLine(funcLine);
			
			writer.WriteLine();	
		}
		writer.WriteLine("    }");
		writer.WriteLine("}");
	}

}

